const headerPropertiesTypes = {
    GET_HEADER_PROPERTIES: 'GET_HEADER_PROPERTIES',
    SET_HEADER_PROPERTIES: 'SET_HEADER_PROPERTIES',
    SET_HEADER_DISPLAY: 'SET_HEADER_DISPLAY',
    SET_HEADER_TRANSPARENT: 'SET_HEADER_TRANSPARENT',
    SET_HEADER_THEME: 'SET_HEADER_THEME',
    SET_HEADER_FIXED: 'SET_HEADER_FIXED'
}

export default headerPropertiesTypes;