const websitePropertiesTypes = {
    GET_WEBSITE_PROPERTIES: 'GET_WEBSITE_PROPERTIES',
    SET_WEBSITE_PROPERTIES: 'SET_WEBSITE_PROPERTIES',
    SET_WEBSITE_NAME: 'SET_WEBSITE_NAME'
}

export default websitePropertiesTypes;